name: Test & Coverage Badges
on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run unit tests with coverage (produce coverage-summary.json)
        run: npm run test:ci

      - name: Update README coverage badges
        run: npm run test:badge

      - name: Commit README update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[TEST] update test coverage'
          branch: dev
          file_pattern: README.md
